# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set a working directory
WORKDIR /app

# Copy all files to the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir google google-api-python-client google-auth-httplib2 google-auth-oauthlib mcp[cli] pydantic python-dotenv pydantic[email]

# Set environment variables placeholders (they will be overridden by startCommand config)
ENV GOOGLE_API_KEY=changeme
ENV GOOGLE_CSE_ID=changeme
ENV GOOGLE_CLIENT_ID=changeme
ENV GOOGLE_CLIENT_SECRET=changeme
ENV GOOGLE_REFRESH_TOKEN=changeme

# Command to run the MCP server
CMD ["python", "server.py"]
